.\" Manpage for jrnl

.TH jrnl 1 "January 2019" "" ""

.SH NAME
jrnl \- write a journal

.SH SYNOPSIS
\fBjrnl\fR [\fIDATES\fI] [\fIOPTIONS\fR]

.SH DESCRIPTION
\fIjrnl\fR is a program to help manage a personal journal. This needs a configuration file to run, which can be generated with the \fI--setup\fR option.

.SH DATES
If you don't supply any dates, \fIjrnl\fR will open a journal entry for today's date and, if you tell it to, write a timestamp at right now's time. Otherwise you can specify a number of dates to open using a combination of any sensible date format or an integer offset from today's date.

You can also open the lastest existing journal entry with \fIHEAD\fR, and access journal entry ancestors of any date corresponding to an existing entry with \fI^\fR or \fI~N\fR date suffixes. To open an existing entry closest to a specified date, prepend that date argument with \fI@\fR.

If you do specify dates, by default this will not create new entries, but you can change this behavior in the config file.

.SH OPTIONS
.
.TP
\fB-e --editor\fR
specify editor to open entry with
.
.
.TP
\fB-h --help\fR
show help message and exit
.
.
.TP
\fB--setup\fR
print configuration file and exit
.
.
.TP
\fB-t --timestamp\fR
write a timestamp before opening editor
.
.
.TP
\fB--no-timestamp\fR
don't write a timestamp before opening editor
.
.
.TP
\fB--version\fR
show program's version number and exit
.

.SH COMMANDS
.
.TP
\fBjrnl grep\fR
print lines from the journal matching a pattern. Runs grep with the -r (recursive) and -I (ignore binary files) options at the journal root; will accept any other grep options.
.

.SH BUGS
No known bugs: please open an issue at \fIgithub.com/mwiens91/jrnl\fR if you find one.

.SH AUTHOR
Matt Wiens <mwiens91 at gmail dot com>
